
   
version: "3.7"
services:
  noip:
    restart: always
    container_name: bukkit
    image: bbriggs/bukkit:1.16.3
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    environment:
      - EULA=true
      
